#✅ [**Numpy Tutorial FreeCodeCamp**](https://youtu.be/QUT1VHiLmmI?si=MPL52O1zAmc7x243)

## Load in Numpy

In [54]:
import numpy as np

In [55]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [56]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [57]:
# Get Dimension
a.ndim

1

In [58]:
# Get Shape
b.shape

(2, 3)

In [59]:
# Get Type
a.dtype

dtype('int32')

In [60]:
# Get Size
a.itemsize

4

In [61]:
# Get total size
a.nbytes

12

In [62]:
# Get number of elements
a.size

3

## Accessing/Changing specific elements, rows, columns, etc

In [63]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [64]:
# Get a specific element [r, c]
a[1, 5]

np.int64(13)

In [65]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [67]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [68]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [69]:
a[1,5] = 20
print(a)


a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-D Example

In [70]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [71]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [72]:
# replace
b[:,1,:] = [[9,9],[8,8]]

In [73]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [74]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Print(b) and only b does the same work of printing

## Initializing Different Types of Arrays

In [75]:
# All 0s matrix
np.zeros((2,3,3,3)) #---> 4D --- like 2 big arrays of 3 sub-big arrays of 3row and 3columns

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [76]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [77]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [78]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [79]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.1672964 , 0.26667617],
       [0.49414065, 0.22860319],
       [0.50288019, 0.28738408],
       [0.98932493, 0.27439811]])

In [80]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-1, -3,  4],
       [ 2,  6,  2],
       [ 1,  0,  7]])

In [81]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [83]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [84]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## Mathematics

In [85]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [86]:
a + 2

array([3, 4, 5, 6])

In [87]:
a - 2

array([-1,  0,  1,  2])

In [88]:
a*2

array([2, 4, 6, 8])

In [89]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [90]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [91]:
a**2

array([ 1,  4,  9, 16])

In [92]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [93]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)


#### Linear Algebra

In [94]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [95]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [96]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

#### Statistics

In [97]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.min(stats)

np.int64(1)

In [99]:
np.max(stats, axis=1)

array([3, 6])

In [100]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Arrays

In [101]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [102]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])